### ISSUE TITLE
Add a controller to Vince

### ISSUE THREAD

**Issue by Tsmith18256** [davethomas11/V_Is_For_Vince#6]
Gotta be able to move Vince around. For now, we can probably just tap the input directly to Vince. Once I have done the TypeScript refactor and extracted the game engine to it's own folder, I can add an input service to the engine that abstracts the keyboard input from the Vince class and I'll add a `Controllable` interface or something that sends the results of that input down to Vince.

**Comment by davethomas11** [comment]
Feature developed in https://github.com/davethomas11/V_Is_For_Vince/pull/16
